name: Bug Report
description: Document an unexpected behavior
title: "[Bug]: "
labels: ["bug"]
projects: ["Nibbles-and-Mlems-Exotics-LLC/2"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise expectation of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What were you trying to do when the bug occurred and what did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can this bug be reproduced?
  - type: dropdown
    attributes:
      label: Platform
      description: What OS(s) are you running on?
      multiple: true
      options:
        - Windows
        - Mac
        - Android
        - iOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Any other information that could be useful.
  - type: markdown
    attributes: 
      value: |
        # Example
        Title: [Bug]: Animal health record entry does not save on mobile version

        Description: When trying to save new health records for animals on the mobile app, the save button appears to work, but the data isn’t retained after navigating away from the page.

        Steps to Reproduce:
          Open the mobile app on an Android device.
          Navigate to the "Health Records" section for an animal.
          Enter new health data (e.g., weight, medication, vet visit).
          Tap the 'Save' button.
          Navigate to another section of the app.
          Return to the "Health Records" section.
        
        Expected Behavior: I expected the entered health data to be saved and displayed when I return to the "Health Records" section.

        Platform: Android

        Additional Context: This issue seems to only happen on mobile devices. I tested the same functionality on the desktop version (Linux, Ubuntu 22.04, Chrome) and it worked as expected. No error messages are shown, and there are no visible crashes. Other data entries (e.g., feeding logs) seem to save correctly on mobile.
