name: Enhancement Request
description: Request a minor change.
title: "[Enhancement]: "
labels: ["enhancement"]
projects: ["Nibbles-and-Mlems-Exotics-LLC/2"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What is the desired change? 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Please provide any additional information that might be useful.
  - type: markdown
    attributes:
      value: |
        ## Example
        Title: [Enhancement]: Optimize database queries for faster animal search
        
        Description: Improve the performance of database queries for animal searches by optimizing the indexing and query structure. Users have reported delays when searching large datasets.
        
        Additional context: Current implementation uses basic queries without indexing, which causes delays in larger data sets.
